BrauneDigital\MailBundle\Entity\UserMail:
    type: entity
    table: user_mails
    manyToOne:
        object:
            targetEntity: BrauneDigital\MailBundle\Model\UserInterface
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            joinColumns:
                object_id:
                    referencedColumnName: id
            orphanRemoval: false
        object2:
            targetEntity: BrauneDigital\MailBundle\Model\UserInterface
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            joinColumns:
                object2_id:
                    referencedColumnName: id
            orphanRemoval: false
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
